### ISSUE TITLE
Error with DeployUtil.makeDeploy()'s CLPublicKey bytes parser @ serializeHeader()

### ISSUE THREAD

**Issue by Levike34** [casper-ecosystem/casper-client-sdk#222]
**Describe the bug**
The CLPublicKey bytes parse in serializeHeader() fails because of how the Uint8Array is formatted with a key-value pair. 

**Expected behavior**
 It should have functionality to format the public key into a normal Uint8Array without the indices.

**Additional context**
This solved my problem.
```
function clKeyToBytes(value: CLPublicKey): Uint8Array {
  const res = Array.from(value.data)
  const res2 = Uint8Array.from(res)

  return concat([Uint8Array.from([value.tag]), res2]);
}
```

**Comment by RitaMAllenCA** [comment]
@hoffmannjan thinking Ryo can address this?

**Comment by hoffmannjan** [comment]
yeah, that will require investigation - he can look into it

**Comment by hoffmannjan** [comment]
@Levike34 I think what you want to achieve can be done by calling [`CLValueParsers.toBytesWithType(<CLPublicKey as argument>)`](https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/lib/CLValue/Abstract.ts#L94-L99) - it will automatically concat `tag` byte. We can't change the default behaviour because standard typed CLValues doesn't contain tag prefix.

**Comment by RitaMAllenCA** [comment]
We can't change the default behaviour because standard typed CLValues doesn't contain tag prefix.
