### ISSUE TITLE
Update CI/CD to autogenerate README docs

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#253]

**Comment by gyroflaw** [comment]
Add auto generated docs to README was done in this [PR](https://github.com/casper-ecosystem/casper-js-sdk/pull/248) but since this PR updated typescript module it fails to build the SDK.
So I created the [PR](https://github.com/casper-ecosystem/casper-js-sdk/pull/255) indicating this issue.
If this PR is merged the docs can be auto generated and added to the README when publish new version of SDK in CI.
Tested on [here](https://github.com/gyroflaw/casper-js-sdk/actions/runs/4230887503/jobs/7348745007)
and this is published test version https://www.npmjs.com/package/casper-js-sdk-test2
