### ISSUE TITLE
[Improvement/Bug?] Tuple3 is inconsistent

### ISSUE THREAD

**Issue by KillianH** [casper-ecosystem/casper-client-sdk#475]
CLValueTuple3 constructor ask for a CLType instead of CLTupleTuple3 (I guess ?)

**Comment by alexmyshchyshyn** [comment]
Hi @KillianH ,

Thank you for reporting the issue! 

- The `CLValueTuple3` constructor now properly requires a `CLTuple3` type instead of a generic `CLType`.

These fixes have been implemented and will be available in the upcoming release: **v5.0.0-beta2**.

If you have any further questions or feedback, feel free to reach out. Thanks for helping us improve! 🚀
